In [13]:
import pandas as pd
import numpy as np
import pandas as pd
from collections import Counter
import re

In [4]:
df = pd.read_csv('Data\Dons.csv')

In [5]:
df

,Dons,Src,Conditions,Avantages
0,À terre à cheval*,AG,"Capacité de classe bond du lancier, 5 rangs en...",Le personnage remonte en selle par une action ...
1,Abondance de révélations,AM,Capacité de classe mystère,Utiliser une unique révélation plus de fois pa...
2,Absorption rageuse,MCA,Capacité à lancer des sorts de sanguin de 2e n...,Le personnage absorbe l'énergie magique des so...
3,Acolyte de la Nature,CCMI,Suivant de la voie de la nature,Les sorts sont plus efficaces sur les plantes
4,Acrobate des corniches,MR,"Dex 13, nain, trait racial montagnard ou stabi...",Déplacement plus rapide sur les espaces restre...
...,...,...,...,...
1412,Voyageur de la tapisserie,RSE,Personnage de niveau 5,Lance les sorts de téléportation avec un plus ...
1413,Xénoglossie,AO,"Int 13, 3 rangs en Linguistique",Utilisation de la linguistique pour communique...
1414,Yeux de lynx,MJRA,"Sag 13, trait racial sens aiguisés",Ignorer jusqu'à -5 de pénalité aux tests de Pe...
1415,Yeux du crépuscule,ISR,"Sens très affûtés, 7 rangs en Perception, trai...",Les créatures dans les zones de lumière faible...
1416,Zélote du refus de mourir*,AG,"For 13, Con 15, demi-orque ou orque, Initié du...",Les ennemis sont obligés de refaire les attaqu...

In [6]:
#Add Id to the dataframe
df['Id'] = np.arange(len(df))

In [7]:
df

,Dons,Src,Conditions,Avantages,Id
0,À terre à cheval*,AG,"Capacité de classe bond du lancier, 5 rangs en...",Le personnage remonte en selle par une action ...,0
1,Abondance de révélations,AM,Capacité de classe mystère,Utiliser une unique révélation plus de fois pa...,1
2,Absorption rageuse,MCA,Capacité à lancer des sorts de sanguin de 2e n...,Le personnage absorbe l'énergie magique des so...,2
3,Acolyte de la Nature,CCMI,Suivant de la voie de la nature,Les sorts sont plus efficaces sur les plantes,3
4,Acrobate des corniches,MR,"Dex 13, nain, trait racial montagnard ou stabi...",Déplacement plus rapide sur les espaces restre...,4
...,...,...,...,...,...
1412,Voyageur de la tapisserie,RSE,Personnage de niveau 5,Lance les sorts de téléportation avec un plus ...,1412
1413,Xénoglossie,AO,"Int 13, 3 rangs en Linguistique",Utilisation de la linguistique pour communique...,1413
1414,Yeux de lynx,MJRA,"Sag 13, trait racial sens aiguisés",Ignorer jusqu'à -5 de pénalité aux tests de Pe...,1414
1415,Yeux du crépuscule,ISR,"Sens très affûtés, 7 rangs en Perception, trai...",Les créatures dans les zones de lumière faible...,1415
1416,Zélote du refus de mourir*,AG,"For 13, Con 15, demi-orque ou orque, Initié du...",Les ennemis sont obligés de refaire les attaqu...,1416

In [22]:
# Create new dataframe and drop Avantages column
df_new = df.drop(columns=['Avantages'])

In [23]:
df_new

,Dons,Src,Conditions,Id
0,À terre à cheval*,AG,"Capacité de classe bond du lancier, 5 rangs en...",0
1,Abondance de révélations,AM,Capacité de classe mystère,1
2,Absorption rageuse,MCA,Capacité à lancer des sorts de sanguin de 2e n...,2
3,Acolyte de la Nature,CCMI,Suivant de la voie de la nature,3
4,Acrobate des corniches,MR,"Dex 13, nain, trait racial montagnard ou stabi...",4
...,...,...,...,...
1412,Voyageur de la tapisserie,RSE,Personnage de niveau 5,1412
1413,Xénoglossie,AO,"Int 13, 3 rangs en Linguistique",1413
1414,Yeux de lynx,MJRA,"Sag 13, trait racial sens aiguisés",1414
1415,Yeux du crépuscule,ISR,"Sens très affûtés, 7 rangs en Perception, trai...",1415
1416,Zélote du refus de mourir*,AG,"For 13, Con 15, demi-orque ou orque, Initié du...",1416

In [25]:
df_new['Conditions_Words'] = df_new['Conditions'].str.lower().apply(lambda x: re.findall(r'\b\w+\b', str(x)))
df_new

,Dons,Src,Conditions,Id,Conditions_Words
0,À terre à cheval*,AG,"Capacité de classe bond du lancier, 5 rangs en...",0,"[capacité, de, classe, bond, du, lancier, 5, r..."
1,Abondance de révélations,AM,Capacité de classe mystère,1,"[capacité, de, classe, mystère]"
2,Absorption rageuse,MCA,Capacité à lancer des sorts de sanguin de 2e n...,2,"[capacité, à, lancer, des, sorts, de, sanguin,..."
3,Acolyte de la Nature,CCMI,Suivant de la voie de la nature,3,"[suivant, de, la, voie, de, la, nature]"
4,Acrobate des corniches,MR,"Dex 13, nain, trait racial montagnard ou stabi...",4,"[dex, 13, nain, trait, racial, montagnard, ou,..."
...,...,...,...,...,...
1412,Voyageur de la tapisserie,RSE,Personnage de niveau 5,1412,"[personnage, de, niveau, 5]"
1413,Xénoglossie,AO,"Int 13, 3 rangs en Linguistique",1413,"[int, 13, 3, rangs, en, linguistique]"
1414,Yeux de lynx,MJRA,"Sag 13, trait racial sens aiguisés",1414,"[sag, 13, trait, racial, sens, aiguisés]"
1415,Yeux du crépuscule,ISR,"Sens très affûtés, 7 rangs en Perception, trai...",1415,"[sens, très, affûtés, 7, rangs, en, perception..."
1416,Zélote du refus de mourir*,AG,"For 13, Con 15, demi-orque ou orque, Initié du...",1416,"[for, 13, con, 15, demi, orque, ou, orque, ini..."

In [26]:
all_words = [word for sublist in df_new['Conditions_Words'] for word in sublist]
word_counts = Counter(all_words)
word_counts

Counter({'de': 906,
         'capacité': 404,
         'en': 368,
         'classe': 314,
         '13': 278,
         'du': 257,
         'bba': 242,
         'à': 231,
         'rangs': 206,
         'ou': 203,
         'science': 165,
         'd': 158,
         'combat': 153,
         '1': 152,
         'niveau': 137,
         'la': 131,
         'des': 127,
         '5': 118,
         '6': 106,
         'lancer': 98,
         'arme': 94,
         'dex': 89,
         'attaque': 86,
         'int': 82,
         'suivant': 80,
         'rang': 75,
         'cha': 70,
         'sorts': 69,
         'mains': 69,
         'orque': 61,
         'for': 60,
         'canalisation': 59,
         'racial': 57,
         'connaissances': 57,
         'nues': 57,
         '3': 57,
         'expertise': 56,
         'trait': 55,
         'énergie': 52,
         '15': 51,
         'une': 50,
         'un': 50,
         'l': 48,
         'prédilection': 47,
         'puissance': 47,
         'magie': 46,
         'maniement': 45,
         'personnage': 45,
         'tir': 45,
         '4': 44,
         'demi': 44,
         '10': 38,
         'armes': 38,
         '11': 37,
         'bluff': 35,
         'et': 34,
         '9': 33,
         'gnome': 33,
         'deux': 33,
         'rage': 31,
         'nls': 31,
         'pouvoir': 30,
         'sag': 30,
         'avec': 30,
         'esquive': 29,
         'halfelin': 29,
         'au': 28,
         'art': 28,
         'elfe': 28,
         'serpent': 27,
         'con': 27,
         'drow': 26,
         '8': 25,
         'magique': 25,
         'représentation': 24,
         'le': 23,
         'école': 23,
         'homme': 23,
         'intimidation': 23,
         'frappe': 23,
         'coup': 23,
         'lutte': 23,
         'nain': 22,
         'bouclier': 21,
         '7': 21,
         'bout': 21,
         'portant': 21,
         'plus': 20,
         'berserker': 20,
         'magiques': 19,
         'dans': 19,
         'renforcée': 19,
         'talent': 19,
         'guerrier': 19,
         'souplesse': 18,
         'réflexes': 18,
         'endurance': 18,
         '12': 17,
         'sournoise': 17,
         'humain': 17,
         'croc': 17,
         'jambe': 17,
         '17': 17,
         'acrobaties': 16,
         'nature': 16,
         'discrétion': 16,
         'alignement': 16,
         'bardique': 16,
         'feinte': 16,
         'psychique': 15,
         'porte': 15,
         'capacités': 15,
         'rapide': 15,
         'attaques': 15,
         'gobelin': 15,
         '2': 14,
         'compagnon': 14,
         'animal': 14,
         'artisanat': 14,
         'tueur': 14,
         'équitation': 13,
         'utilisation': 13,
         'choisie': 13,
         'les': 13,
         'animale': 13,
         'vision': 13,
         'bousculade': 12,
         'dieu': 12,
         'voir': 12,
         'mystères': 12,
         'profanes': 12,
         'enchaînement': 12,
         'ki': 12,
         'supérieure': 12,
         'psychiques': 12,
         'taille': 12,
         'chant': 12,
         'fer': 12,
         'détection': 12,
         'exotique': 11,
         'sensibilité': 11,
         'sang': 11,
         'sous': 11,
         'doit': 11,
         'monté': 11,
         'pouvoirs': 11,
         'divins': 11,
         'familier': 11,
         '3d6': 11,
         'moine': 11,
         'volonté': 11,
         'fourberie': 11,
         'dur': 11,
         'cuire': 11,
         'escamotage': 10,
         'type': 10,
         'inspiration': 10,
         'poisse': 10,
         'fantôme': 10,
         'comme': 10,
         'forme': 10,
         'réserve': 10,
         'force': 10,
         'convocation': 10,
         'imposition': 10,
         '19': 10,
         'décisive': 10,
         'fouet': 10,
         'noblesse': 10,
         'maléfice': 10,
         'persuasion': 9,
         'dimensionnelle': 9,
         'aasimar': 9,
         'non': 9,
         'divinité': 9,
         'port': 9,
         'armure': 9,
         'kobold': 9,
         'entraînement': 9,
         'lanceur': 9,
         'religion': 9,
         'ogre': 9,
         'sort': 9,
         'psychologie': 9,
         'sabotage': 9,
         'regard': 9,
         'oréade': 9,
         'sens': 9,
         'filet': 8,
         'pas': 8,
         'tengu': 8,
         'mal': 8,
         'alchimie': 8,
         'guerre': 8,
         'aveugle': 8,
         'hobgobelin': 8,
         'premiers': 8,
         'secours': 8,
         'chance': 8,
         'rat': 8,
         'maîtrise': 8,
         'main': 8,
         'précision': 8,
         'maître': 8,
         'perception': 8,
         'profession': 8,
         'spirituelle': 8,
         'roublard': 8,
         'aucun': 7,
         'dotée': 7,
         'invocation': 7,
         'ifrit': 7,
         'ondin': 7,
         'texte': 7,
         '16': 7,
         'positive': 7,
         'courage': 7,
         'étourdissant': 7,
         'démonstration': 7,
         'dhampir': 7,
         'armures': 7,
         'sauvage': 7,
         'druide': 7,
         'monstres': 7,
         'combattant': 7,
         'finesse': 7,
         'pièges': 7,
         'déguisement': 7,
         'poison': 7,
         'lignage': 7,
         'p': 7,
         'petit': 7,
         'siège': 7,
         'draconique': 7,
         'froid': 7,
         'sanguine': 6,
         'objets': 6,
         'chakra': 6,
         'sylphe': 6,
         'vol': 6,
         'domaine': 6,
         'survie': 6,
         'connaissance': 6,
         'pierre': 6,
         'fetchelin': 6,
         'n': 6,
         'importe': 6,
         'étudiée': 6,
         'local': 6,
         'plans': 6,
         'bâton': 6,
         'martiale': 6,
         'feu': 6,
         'félin': 6,
         'ennemi': 6,
         'juré': 6,
         '7d6': 6,
         'suprême': 6,
         'choisi': 6,
         'ensorceleur': 6,
         'déluge': 6,
         'sale': 6,
         'vigueur': 6,
         'adepte': 6,
         'loyal': 6,
         'explosion': 6,
         'noir': 6,
         'rôdeur': 6,
         'fronde': 6,
         'vigilance': 6,
         'possession': 6,
         'mystère': 5,
         'chassé': 5,
         'extérieur': 5,
         'monture': 5,
         'aura': 5,
         'diplomatie': 5,
         'eidolon': 5,
         'improvisé': 5,
         'vénérer': 5,
         'naturelle': 5,
         'exploration': 5,
         'souterraine': 5,
         'don': 5,
         'initiative': 5,
         'vitesse': 5,
         'spéciale': 5,
         'trois': 5,
         'spécialisation': 5,
         'uniquement': 5,
         'intimidante': 5,
         'aspect': 5,
         'goule': 5,
         'prêtre': 5,
         '6d6': 5,
         'châtiment': 5,
         'bon': 5,
         'coassement': 5,
         'spécial': 5,
         'zon': 5,
         'kuthon': 5,
         'coups': 5,
         'dimensionnel': 5,
         'surhumains': 5,
         'utiliser': 5,
         'hypnotiseur': 5,
         'duergar': 5,
         'bonus': 5,
         'folklore': 5,
         'aux': 5,
         'éventration': 5,
         'troll': 5,
         'cinétique': 5,
         'hypnotique': 5,
         'moins': 5,
         'jugement': 5,
         'ingénieur': 5,
         'géant': 5,
         'linguistique': 5,
         'mauvais': 5,
         'estimation': 5,
         'morts': 5,
         '2e': 4,
         'initié': 4,
         'angélique': 4,
         'rovagug': 4,
         'utilisée': 4,
         'tieffelin': 4,
         'boucliers': 4,
         'divination': 4,
         'agilité': 4,
         'ténèbres': 4,
         '2d6': 4,
         'cible': 4,
         'chaîne': 4,
         'cloutée': 4,
         'désarmement': 4,
         'briser': 4,
         'registre': 4,
         'seigneur': 4,
         'négative': 4,
         'focalisation': 4,
         'funeste': 4,
         'renversement': 4,
         'bourbiérin': 4,
         'terrifiant': 4,
         'empathie': 4,
         'enquêteur': 4,
         'membre': 4,
         'poisons': 4,
         'être': 4,
         '18': 4,
         'amélioration': 4,
         'créatures': 4,
         'convoquées': 4,
         'alliés': 4,
         'naturels': 4,
         'poing': 4,
         'prudent': 4,
         'destruction': 4,
         'g': 4,
         'sorcière': 4,
         'danse': 4,
         'affinité': 4,
         'aisance': 4,
         'assaut': 4,
         '3e': 4,
         'dressage': 4,
         'base': 4,
         'soudain': 4,
         'spirituel': 4,
         'totale': 4,
         'étrange': 4,
         'héritage': 4,
         'nocturne': 4,
         'étreinte': 4,
         'grâce': 4,
         'haine': 4,
         'ingénierie': 4,
         'dons': 4,
         'or': 4,
         'préparer': 4,
         'aiguisés': 4,
         'voie': 3,
         'férocité': 3,
         'éveiller': 3,
         'ailes': 3,
         'doigts': 3,
         'fée': 3,
         'partage': 3,
         'charge': 3,
         'élu': 3,
         'pacte': 3,
         'divin': 3,
         'torag': 3,
         'morsure': 3,
         'shélyn': 3,
         'hanté': 3,
         'gozreh': 3,
         'naturelles': 3,
         'bénédictions': 3,
         'aligenement': 3,
         'divergeant': 3,
         'maximum': 3,
         'cran': 3,
         'celui': 3,
         'découverte': 3,
         'alchimiste': 3,
         '5d6': 3,
         'briseur': 3,
         'urgathoa': 3,
         'perturbateur': 3,
         'neutre': 3,
         'érastil': 3,
         'irori': 3,
         'norgorber': 3,
         'cayden': 3,
         'cailéan': 3,
         'pharasma': 3,
         'asmodéus': 3,
         'iomédae': 3,
         'calistria': 3,
         '4d6': 3,
         'gorum': 3,
         'parade': 3,
         'géographie': 3,
         'dv': 3,
         'mentale': 3,
         'jouer': 3,
         'galop': 3,
         '25': 3,
         'fabuleux': 3,
         'riposte': 3,
         'canalisé': 3,
         'spectacle': 3,
         'amateur': 3,
         'vampire': 3,
         'qui': 3,
         'incantation': 3,
         'empire': 3,
         'décadent': 3,
         'lutteur': 3,
         '14': 3,
         'débrouillardise': 3,
         'défensif': 3,
         'tonnerres': 3,
         'jumeaux': 3,
         'utilisées': 3,
         'corps': 3,
         'surhumaine': 3,
         'détournement': 3,
         'abadar': 3,
         'fiélonne': 3,
         'épée': 3,
         'dissipation': 3,
         'évasion': 3,
         'allié': 3,
         'choix': 3,
         'harmonie': 3,
         'naga': 3,
         'créature': 3,
         'raciale': 3,
         'constriction': 3,
         'étudié': 3,
         'sahir': 3,
         'afiyun': 3,
         'addict': 3,
         'pesh': 3,
         'mineure': 3,
         'distance': 3,
         'traqueur': 3,
         'clair': 3,
         'lune': 3,
         'voltigeur': 3,
         'buveur': 3,
         'par': 3,
         'divine': 3,
         'néthys': 3,
         'adaptative': 3,
         'cauchemar': 3,
         'repositionnement': 3,
         'fatale': 3,
         'imitation': 3,
         'induction': 3,
         'souvenir': 3,
         'lacération': 3,
         'furieuse': 3,
         'talents': 3,
         'magicien': 3,
         'duel': 3,
         'vivants': 3,
         'refus': 3,
         'mourir': 3,
         'astuce': 3,
         'ninja': 3,
         'cachée': 3,
         'supérieur': 3,
         'kitsune': 3,
         'présence': 3,
         'régénération': 3,
         'histoire': 3,
         'subtilisation': 3,
         'sanguin': 2,
         'son': 2,
         'souffle': 2,
         '1d6': 2,
         'apparition': 2,
         'effrayante': 2,
         'natif': 2,
         'chair': 2,
         'trépanation': 2,
         'créer': 2,
         'soins': 2,
         'spontanément': 2,
         'conscience': 2,
         'robuste': 2,
         'phrénique': 2,
         'arcane': 2,
         'magus': 2,
         'recevoir': 2,
         'vénère': 2,
         'formation': 2,
         'sacrée': 2,
         'traversée': 2,
         'ombres': 2,
         'création': 2,
         'suli': 2,
         'curiosité': 2,
         'intrépide': 2,
         'escalade': 2,
         'éclair': 2,
         'possède': 2,
         'ardentes': 2,
         's': 2,
         'avancer': 2,
         'nage': 2,
         'grande': 2,
         'majeur': 2,
         'bombe': 2,
         'retardement': 2,
         'bombes': 2,
         'infernal': 2,
         'griffes': 2,
         'projectiles': 2,
         'mâchoire': 2,
         '21': 2,
         'eau': 2,
         'terre': 2,
         'inquisiteur': 2,
         'desna': 2,
         'fureur': 2,
         'téléportation': 2,
         'tête': 2,
         'dure': 2,
         'reine': 2,
         'sarenraé': 2,
         'insolente': 2,
         'occultiste': 2,
         '1er': 2,
         'exploit': 2,
         'opportune': 2,
         'lamashtu': 2,
         'sac': 2,
         'vocal': 2,
         'niveaux': 2,
         'confère': 2,
         'savoir': 2,
         'déclamation': 2,
         'pendant': 2,
         'dégagement': 2,
         'grand': 2,
         'gorgone': 2,
         'alcoolisé': 2,
         'lézard': 2,
         'enchaîner': 2,
         'gobelins': 2,
         'démoralisant': 2,
         'griffe': 2,
         'déplacement': 2,
         'loin': 2,
         'tactique': 2,
         'obédience': 2,
         'creuseur': 2,
         'terrier': 2,
         'falcata': 2,
         'robustesse': 2,
         'protection': 2,
         'combative': 2,
         'utilisé': 2,
         'effet': 2,
         'humanoïde': 2,
         'sérénité': 2,
         'marin': 2,
         'avoir': 2,
         'été': 2,
         'chaotique': 2,
         'surnaturelle': 2,
         'ans': 2,
         'arcaniste': 2,
         'barde': 2,
         'obtenir': 2,
         'aptitude': 2,
         'impudent': 2,
         'télépathie': 2,
         'jour': 2,
         'pour': 2,
         'semelle': 2,
         'dorn': 2,
         'dergar': 2,
         'naine': 2,
         'révélation': 2,
         'frénésie': 2,
         'sahuagin': 2,
         'augure': 2,
         'apprentissage': 2,
         'mineur': 2,
         'précis': 2,
         'nécromancie': 2,
         'second': 2,
         'jet': 2,
         'langue': 2,
         'diable': 2,
         'peau': 2,
         'intermédiaires': 2,
         'surprise': 2,
         'poussée': 2,
         'hydraulique': 2,
         'derviche': 2,
         'marteau': 2,
         'talentueuse': 2,
         'métamagie': 2,
         'dernier': 2,
         'rempart': 2,
         'exilé': 2,
         'manoeuvres': 2,
         'agiles': 2,
         'raciaux': 2,
         'acrobatique': 2,
         'légères': 2,
         'regroupement': 2,
         'réduction': 2,
         'dégâts': 2,
         'né': 2,
         'sévère': 2,
         'mouvement': 2,
         'résistance': 2,
         'samsaran': 2,
         'élémentaire': 2,
         'succession': 2,
         'enchaînements': 2,
         'lasso': 2,
         'wayang': 2,
         '18m': 2,
         'obscure': 2,
         'bond': 1,
         'lancier': 1,
         'montagnard': 1,
         'stabilité': 1,
         'retenir': 1,
         'discipline': 1,
         'cœur': 1,
         'pieds': 1,
         'rapides': 1,
         'ennemis': 1,
         'jurés': 1,
         'illusion': 1,
         'aérien': 1,
         'ange': 1,
         'strix': 1,
         'tailladées': 1,
         'extraits': 1,
         'blessure': 1,
         'flore': 1,
         'faune': 1,
         'aîné': 1,
         'amplification': 1,
         'ancrage': 1,
         'impitoyable': 1,
         'reçoit': 1,
         'toutes': 1,
         'reptilien': 1,
         'versatilité': 1,
         'artistique': 1,
         'imprévisible': 1,
         'flamme': 1,
         'intérieure': 1,
         'quatre': 1,
         'cavaliers': 1,
         'poursuite': 1,
         'folkllore': 1,
         'hache': 1,
         'apsu': 1,
         'accès': 1,
         'canalisaiton': 1,
         'chat': 1,
         'leste': 1,
         'bestial': 1,
         'bestiales': 1,
         'odieux': 1,
         'contre': 1,
         'panache': 1,
         'os': 1,
         'bénédiction': 1,
         'air': 1,
         'nécromancienou': 1,
         'ghlaunder': 1,
         '8d6': 1,
         'démon': 1,
         'gyronna': 1,
         'tg': 1,
         'concentration': 1,
         'malgré': 1,
         'casque': 1,
         'bosselé': 1,
         'kyton': 1,
         'archidiable': 1,
         'duc': 1,
         'malebranche': 1,
         'catin': 1,
         'individu': 1,
         'chanceux': 1,
         'adaptable': 1,
         'piétinement': 1,
         'chevaucheur': 1,
         'cornes': 1,
         'dragon': 1,
         'dahak': 1,
         'poisson': 1,
         'lourdes': 1,
         'chute': 1,
         'ralentie': 1,
         'supersonique': 1,
         'dompteur': 1,
         'archétype': 1,
         'collectionneur': 1,
         'furie': 1,
         'vent': 1,
         'mythique': 1,
         'compétence': 1,
         'compréhension': 1,
         'conducteur': 1,
         'véhicule': 1,
         'guilde': 1,
         'empoisonneurs': 1,
         'paladin': 1,
         'serf': 1,
         'service': 1,
         'anticipée': 1,
         'conjurateur': 1,
         'travailler': 1,
         'mois': 1,
         'sur': 1,
         'navire': 1,
         'corsaire': 1,
         'célèbre': 1,
         'méduse': 1,
         'nagaji': 1,
         'préparation': 1,
         'potions': 1,
         'sanctification': 1,
         'profanation': 1,
         'scène': 1,
         'chaînes': 1,
         'cimeterre': 1,
         'quelle': 1,
         'allonge': 1,
         'découvertes': 1,
         'intangible': 1,
         'dictature': 1,
         'militaire': 1,
         'athéiste': 1,
         'royaumes': 1,
         'indépendants': 1,
         'opérations': 1,
         'tranchante': 1,
         'tunnels': 1,
         'facilité': 1,
         'types': 1,
         'elfique': 1,
         'chaos': 1,
         'bien': 1,
         'loi': 1,
         'redirigé': 1,
         'différentes': 1,
         'mensonges': 1,
         'longue': 1,
         'prudente': 1,
         'discret': 1,
         'dissimulation': 1,
         'changelin': 1,
         'rusée': 1,
         'douloureux': 1,
         'targe': 1,
         'surprenante': 1,
         'est': 1,
         'matériau': 1,
         'primitif': 1,
         'efficacité': 1,
         'accrue': 1,
         'élément': 1,
         'renforcé': 1,
         'embuscade': 1,
         'prestige': 1,
         'contacts': 1,
         'pègre': 1,
         'vipère': 1,
         'enchantement': 1,
         'immobiliser': 1,
         'métamorphose': 1,
         'esclave': 1,
         'galère': 1,
         'gardien': 1,
         'étendues': 1,
         'sauvages': 1,
         'larme': 1,
         'chasseur': 1,
         'double': 1,
         '100': 1,
         '9e': 1,
         '4e': 1,
         'exploitation': 1,
         'explorer': 1,
         'partie': 1,
         'caves': 1,
         'marécage': 1,
         'centre': 1,
         'naval': 1,
         'oracle': 1,
         'déesse': 1,
         'visages': 1,
         'interférence': 1,
         'spirite': 1,
         'fraternité': 1,
         'courte': 1,
         'frémissement': 1,
         'pensées': 1,
         'fils': 1,
         'ombre': 1,
         'arc': 1,
         'long': 1,
         'utilisables': 1,
         'fois': 1,
         'flexibilité': 1,
         'martialle': 1,
         'santé': 1,
         'régiment': 1,
         'diamant': 1,
         'instruments': 1,
         'pointes': 1,
         'tisseur': 1,
         'lueur': 1,
         'féerique': 1,
         'sprinter': 1,
         'défenses': 1,
         'puissante': 1,
         'désespéré': 1,
         'inspirée': 1,
         'esprits': 1,
         'rapière': 1,
         'lamétoile': 1,
         'destrier': 1,
         'ne': 1,
         'environnement': 1,

In [27]:
word_counts.most_common(10)

[('de', 906),
 ('capacité', 404),
 ('en', 368),
 ('classe', 314),
 ('13', 278),
 ('du', 257),
 ('bba', 242),
 ('à', 231),
 ('rangs', 206),
 ('ou', 203)]

In [32]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in C:\Users\adoyet\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\adoyet\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (8.4.1)
Collecting joblib (from nltk)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\adoyet\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in C:\Users\adoyet\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\adoyet\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 16.3 MB/s  0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: joblib, nltk

   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   ---------------------------------------- 0/2 [joblib]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed joblib-1.5.3 nltk-3.10.3

In [33]:
import nltk
from nltk.util import ngrams

In [34]:
# 1. Generate Bigrams (pairs) and Trigrams (triplets)
bigrams_list = []
trigrams_list = []

for sublist in df_new['Conditions_Words']:
    bigrams_list.extend(list(ngrams(sublist, 2)))
    trigrams_list.extend(list(ngrams(sublist, 3)))

# 2. Count frequencies
bigram_counts = Counter(bigrams_list)
trigram_counts = Counter(trigrams_list)

print("--- Top 10 Most Common Bigrams ---")
for bg, count in bigram_counts.most_common(10):
    print(f"{' '.join(bg)}: {count}")

print("\n--- Top 10 Most Common Trigrams ---")
for tg, count in trigram_counts.most_common(10):
    print(f"{' '.join(tg)}: {count}")

--- Top 10 Most Common Bigrams ---
de classe: 303
capacité de: 288
rangs en: 203
de la: 116
de niveau: 116
du combat: 114
capacité à: 107
science du: 99
à lancer: 87
5 rangs: 80

--- Top 10 Most Common Trigrams ---
capacité de classe: 288
capacité à lancer: 86
5 rangs en: 78
1 rang en: 74
science du combat: 61
du combat à: 60
science de la: 56
combat à mains: 55
à mains nues: 55
expertise du combat: 53

In [ ]:
import sys
sys.path.append(".")

from collections import Counter

from pf1_dons.data_loader import load_catalog
from pf1_dons.models import OrGroup
from pf1_dons.engine import Character, filter_feats

catalog = load_catalog()
print("Dons chargés (hors #ERROR!):", len(catalog))

type_counts = Counter()
for feat in catalog:
    for req in feat.parsed.requirements:
        items = req.options if isinstance(req, OrGroup) else [req]
        for o in items:
            type_counts[o.type.value] += 1

for t, c in type_counts.most_common():
    print(f"{t}: {c}")

unparsed_feats = sum(1 for f in catalog if f.parsed.has_unparsed)
print(f"Dons avec au moins un segment UNPARSED: {unparsed_feats} ({100*unparsed_feats/len(catalog):.1f}%)")

In [ ]:
# Exemple : personnage de test -> liste de dons filtrée
perso = Character(
    character_class="Guerrier",
    level=5,
    race="nain",
    ability_scores={"Dex": 13, "For": 15, "Con": 14},
    known_feats={"Esquive"},
)
grouped = filter_feats(perso, catalog)
for status, results in grouped.items():
    print(status, len(results))

grouped["eligible"][:10]